version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node
    expose:
      - "8000" # Bind port 8000 to localhost for Nginx
      - "8020" # Bind port 8020 to localhost for Nginx
      # Other graph-node ports are not exposed to the host to restrict external access
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "mainnet:${FLARE_RPC}"
      GRAPH_LOG: info
  ipfs:
    image: ipfs/kubo:v0.14.0
    expose:
      - "5001"
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres:14
    expose:
      - "5432"
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200",
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "8020:8020"
      - "5001:5001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/modular-config:/etc/nginx/conf.d
      - ./nginx/entrypoint.sh:/docker-entrypoint.d/entrypoint.sh
    environment:
      - BEARER_TOKEN=${BEARER_TOKEN}
    command: ["/docker-entrypoint.d/entrypoint.sh"]
    depends_on:
      - graph-node
